name: Run JMeter Api update

on: [push] 

jobs:
  jmeter_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup-jmeter
        run: |
          sudo apt-get update
          sudo apt install curl -y
          sudo apt install -y default-jdk
          sudo curl -O https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.3.tgz 
          sudo tar -xvf apache-jmeter-5.3.tgz
          
      - name: run-jmeter-test
        run: |
          $GITHUB_WORKSPACE/apache-jmeter-5.3/bin/./jmeter.sh -n -t ApiUpdateFiles.jmx -l result.jtl
