name: Run JMeter Api update

on: [push] 

jobs:
  jmeter_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download and install JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
        tar -xvzf apache-jmeter-5.6.2.tgz
        echo 'export PATH=$PATH:$PWD/apache-jmeter-5.6.2/bin' >> ~/.bashrc
        source ~/.bashrc

    - name: Run JMeter tests
      run: |
        jmeter -n -t ApiUpdateFiles.jmx -l results.jtl
