name: Run JMeter Api update

on: [push] 

jobs:
  jmeter_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download and install JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xf apache-jmeter-5.4.1.tgz
        echo 'export PATH=$PATH:$PWD/apache-jmeter-5.4.1/bin' >> ~/.bashrc
        source ~/.bashrc

    - name: Run JMeter tests
      run: |
        jmeter -v
